-- Módulo Integração — SysEmp + Mercado Livre + ETL. Ver Specs/spec_modulo_integracao.md.

-- ---- Infraestrutura de sincronização ----

CREATE TABLE IF NOT EXISTS integracao_log (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    entidade        VARCHAR(50) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'iniciado', -- iniciado | sucesso | erro | cancelado
    qtde_registros  INT UNSIGNED NULL,
    mensagem        TEXT NULL,
    duracao_ms      INT UNSIGNED NULL,
    executado_em    DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_entidade (entidade),
    INDEX idx_executado_em (executado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS integracao_log_detalhe (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    id_log          INT NOT NULL,
    pagina          INT UNSIGNED NULL,
    qtde_registros  INT UNSIGNED NULL,
    status          VARCHAR(10) NOT NULL, -- ok | erro
    mensagem        TEXT NULL,
    duracao_ms      INT UNSIGNED NULL,
    request_body    TEXT NULL,
    criado_em       DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_log) REFERENCES integracao_log(id) ON DELETE CASCADE,
    INDEX idx_log (id_log)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_fila_config (
    chave                 VARCHAR(50) PRIMARY KEY,
    nome                  VARCHAR(150) NOT NULL,
    tipo_tabela           SMALLINT UNSIGNED NOT NULL,
    endpoint_fila         VARCHAR(150) NOT NULL DEFAULT '/listarFila',
    endpoint_detalhe      VARCHAR(150) NULL,
    campo_id_detalhe      VARCHAR(50) NULL,
    endpoint_confirmacao  VARCHAR(150) NOT NULL DEFAULT '/updateFilaApi',
    limite_pagina         INT UNSIGNED NOT NULL DEFAULT 50,
    ativo                 BOOLEAN DEFAULT TRUE,
    observacoes           VARCHAR(255) NULL,
    atualizado_em         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_fila (
    id_fila                          INT PRIMARY KEY,
    tipo_tabela                      SMALLINT UNSIGNED NOT NULL,
    desc_tipo_tabela                 VARCHAR(100) NULL,
    acao                              CHAR(1) NOT NULL, -- I | U | D
    desc_acao                         VARCHAR(60) NULL,
    id_registro                       INT NOT NULL,
    status_sysemp                     VARCHAR(20) NULL,
    datahora_criacao_sysemp           DATETIME NULL,
    datahora_processamento_sysemp     DATETIME NULL,
    consumido                         BOOLEAN DEFAULT FALSE,
    consumido_em                      DATETIME NULL,
    erro_consumo                      VARCHAR(500) NULL,
    confirmado_sysemp                 BOOLEAN DEFAULT FALSE,
    confirmado_em                     DATETIME NULL,
    erro_confirmacao                  VARCHAR(500) NULL,
    importado_em                      DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em                     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_tipo_consumido (tipo_tabela, consumido),
    INDEX idx_tipo_confirmado (tipo_tabela, confirmado_sysemp),
    INDEX idx_id_registro (id_registro)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- Entidades SysEmp ----

CREATE TABLE IF NOT EXISTS sysemp_empresa (
    id_empresa      INT PRIMARY KEY,
    razao_social    VARCHAR(255) NOT NULL,
    fantasia        VARCHAR(255) NULL,
    cnpj            VARCHAR(20) NULL,
    insc_estadual   VARCHAR(30) NULL,
    endereco        VARCHAR(255) NULL,
    numero          VARCHAR(20) NULL,
    bairro          VARCHAR(100) NULL,
    cep             VARCHAR(15) NULL,
    cidade          VARCHAR(100) NULL,
    uf              CHAR(2) NULL,
    telefone        VARCHAR(30) NULL,
    email           VARCHAR(150) NULL,
    ativa           BOOLEAN DEFAULT TRUE,
    grupo_empresa   VARCHAR(5) NULL,
    filial_id       INT NULL,
    synced_at       DATETIME NOT NULL,
    criado_em       DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (filial_id) REFERENCES filiais(id) ON DELETE SET NULL,
    INDEX idx_cnpj (cnpj),
    INDEX idx_ativa (ativa),
    INDEX idx_grupo_empresa (grupo_empresa)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_representante (
    id_representante    INT PRIMARY KEY,
    nome_representante  VARCHAR(255) NOT NULL,
    ativo               BOOLEAN DEFAULT TRUE,
    synced_at           DATETIME NOT NULL,
    criado_em           DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ativo (ativo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_produto (
    id_produto                    INT PRIMARY KEY,
    codigo_auxiliar               VARCHAR(50) NULL,
    nome_produto                  VARCHAR(255) NOT NULL,
    unidade                       VARCHAR(10) NULL,
    tipo_produto                  VARCHAR(100) NULL,
    cod_produto_pai               INT NULL,
    codigo_barras                 VARCHAR(50) NULL,
    codigo_marca                  VARCHAR(50) NULL,
    descricao_marca               VARCHAR(255) NULL,
    codigo_categoria              VARCHAR(50) NULL,
    descricao_categoria           VARCHAR(255) NULL,
    codigo_grupo                  VARCHAR(50) NULL,
    descricao_grupo               VARCHAR(255) NULL,
    codigo_subgrupo               VARCHAR(50) NULL,
    descricao_subgrupo            VARCHAR(255) NULL,
    produto_kit                   BOOLEAN DEFAULT FALSE,
    produto_temfilhos             BOOLEAN DEFAULT FALSE,
    ncm                           VARCHAR(20) NULL,
    peso_liquido                  DECIMAL(12,4) NULL,
    altura                        DECIMAL(12,4) NULL,
    largura                       DECIMAL(12,4) NULL,
    comprimento                   DECIMAL(12,4) NULL,
    qtde_embalagem                DECIMAL(12,4) NULL,
    ativo                         BOOLEAN DEFAULT TRUE,
    synced_at   DATETIME NOT NULL,
    criado_em   DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_codigo_barras (codigo_barras),
    INDEX idx_codigo_auxiliar (codigo_auxiliar),
    INDEX idx_ativo (ativo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_produto_origem (
    id_produto         INT NOT NULL,
    id_empresa         INT NOT NULL,
    origem_mercadoria  TINYINT UNSIGNED NULL,
    synced_at          DATETIME NOT NULL,
    PRIMARY KEY (id_produto, id_empresa),
    FOREIGN KEY (id_produto) REFERENCES sysemp_produto(id_produto) ON DELETE CASCADE,
    FOREIGN KEY (id_empresa) REFERENCES sysemp_empresa(id_empresa) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_produto_categoria_fiscal (
    id_produto     INT NOT NULL,
    id_empresa     INT NOT NULL,
    id_tes_saida   INT NULL,
    synced_at      DATETIME NOT NULL,
    PRIMARY KEY (id_produto, id_empresa),
    FOREIGN KEY (id_produto) REFERENCES sysemp_produto(id_produto) ON DELETE CASCADE,
    FOREIGN KEY (id_empresa) REFERENCES sysemp_empresa(id_empresa) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_produto_estoque (
    id_produto        INT NOT NULL,
    id_empresa        INT NOT NULL,
    estoque_maximo    DECIMAL(14,4) NULL,
    estoque_minimo    DECIMAL(14,4) NULL,
    synced_at         DATETIME NOT NULL,
    PRIMARY KEY (id_produto, id_empresa),
    FOREIGN KEY (id_produto) REFERENCES sysemp_produto(id_produto) ON DELETE CASCADE,
    FOREIGN KEY (id_empresa) REFERENCES sysemp_empresa(id_empresa) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_parceiro (
    id_parceiro             INT PRIMARY KEY,
    class_cliente           BOOLEAN DEFAULT FALSE,
    class_fornecedor        BOOLEAN DEFAULT FALSE,
    class_transportadora    BOOLEAN DEFAULT FALSE,
    razao_social            VARCHAR(255) NOT NULL,
    fantasia                VARCHAR(255) NULL,
    cpf_cnpj                VARCHAR(20) NULL,
    tipo_pessoa             VARCHAR(20) NULL,
    insc_estadual           VARCHAR(30) NULL,
    insc_municipal          VARCHAR(30) NULL,
    contato_nome            VARCHAR(150) NULL,
    sexo                    CHAR(1) NULL,
    data_nascimento         DATE NULL,
    telefone1               VARCHAR(30) NULL,
    telefone2               VARCHAR(30) NULL,
    data_cadastro           DATE NULL,
    logradouro              VARCHAR(255) NULL,
    logradouro_numero       VARCHAR(20) NULL,
    logradouro_complemento  VARCHAR(100) NULL,
    logradouro_bairro       VARCHAR(100) NULL,
    logradouro_municipio    VARCHAR(100) NULL,
    logradouro_uf           CHAR(2) NULL,
    logradouro_cep          VARCHAR(15) NULL,
    logradouro_referencia   VARCHAR(255) NULL,
    logradouro_codigo_ibge  VARCHAR(20) NULL,
    ativo                   BOOLEAN DEFAULT TRUE,
    synced_at   DATETIME NOT NULL,
    criado_em   DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_cpf_cnpj (cpf_cnpj),
    INDEX idx_razao_social (razao_social),
    INDEX idx_class_cliente (class_cliente),
    INDEX idx_class_fornecedor (class_fornecedor),
    INDEX idx_class_transportadora (class_transportadora),
    INDEX idx_ativo (ativo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_preco (
    id                      INT AUTO_INCREMENT PRIMARY KEY,
    id_produto              INT NOT NULL,
    id_tb_preco             INT NULL,
    nome_tabela             VARCHAR(150) NULL,
    nome_condicao           VARCHAR(150) NULL,
    preco_tabela            DECIMAL(18,4) NULL,
    preco_promocao          DECIMAL(18,4) NULL,
    data_inicio_promocao    DATE NULL,
    data_termino_promocao   DATE NULL,
    synced_at               DATETIME NOT NULL,
    criado_em               DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_id_produto (id_produto),
    INDEX idx_id_tb_preco (id_tb_preco)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_pedido (
    id_nota_saida               INT PRIMARY KEY,
    id_empresa                  INT NULL,
    numero_pedido_sysemp        VARCHAR(30) NULL,
    numero_pedido_marketplace   VARCHAR(100) NULL,
    data_pedido                 DATE NULL,
    tipo_pedido                 VARCHAR(30) NULL,
    id_parceiro_cliente         INT NULL,
    id_parceiro_vendedor        INT NULL,
    id_parceiro_transportadora  INT NULL,
    valor_total_nota            DECIMAL(14,4) NULL,
    valor_frete                 DECIMAL(14,4) NULL,
    valor_comissao              DECIMAL(14,4) NULL,
    valor_desconto              DECIMAL(14,4) NULL,
    data_venda                  DATE NULL,
    canal_venda                 VARCHAR(150) NULL,
    data_entrega                DATE NULL,
    mensagem_nota                VARCHAR(255) NULL,
    synced_at   DATETIME NOT NULL,
    criado_em   DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_data_pedido (data_pedido),
    INDEX idx_tipo_pedido (tipo_pedido),
    INDEX idx_id_empresa (id_empresa),
    INDEX idx_id_parceiro_cliente (id_parceiro_cliente)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_pedido_item (
    id                       INT AUTO_INCREMENT PRIMARY KEY,
    id_nota_saida            INT NOT NULL,
    id_empresa               INT NULL,
    numero_pedido_sysemp     VARCHAR(30) NULL,
    id_produto               INT NULL,
    quantidade               DECIMAL(14,4) NULL,
    valor_unitario_liquido   DECIMAL(14,4) NULL,
    valor_unitario_bruto     DECIMAL(14,4) NULL,
    valor_frete              DECIMAL(14,4) NULL,
    valor_comissao           DECIMAL(14,4) NULL,
    quantidade_reservada     DECIMAL(14,4) NULL,
    synced_at                DATETIME NOT NULL,
    INDEX idx_id_nota_saida (id_nota_saida),
    INDEX idx_id_produto (id_produto)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_nota_fiscal (
    id_nota_saida             INT PRIMARY KEY,
    marketplace_pedido        VARCHAR(50) NULL,
    id_empresa                INT NULL,
    nota_serie_danfe          VARCHAR(10) NULL,
    nota_numero               VARCHAR(30) NULL,
    id_cliente                INT NULL,
    entrada_saida             CHAR(1) NULL,
    nota_cfop                 VARCHAR(10) NULL,
    nota_cadastro             DATE NULL,
    nota_emissao              DATE NULL,
    nota_saida                DATE NULL,
    cfop_descricao            VARCHAR(255) NULL,
    status_nota               VARCHAR(10) NULL,
    total_produtos            DECIMAL(14,4) NULL,
    total_servicos            DECIMAL(14,4) NULL,
    total_produtos_servicos   DECIMAL(14,4) NULL,
    vr_frete                  DECIMAL(14,4) NULL,
    valor_frete_seller        DECIMAL(14,4) NULL,
    valor_comissao            DECIMAL(14,4) NULL,
    vr_outros                 DECIMAL(14,4) NULL,
    vr_acrescimo              DECIMAL(14,4) NULL,
    vr_desconto               DECIMAL(14,4) NULL,
    valor_nota                DECIMAL(14,4) NULL,
    volume_qtde               DECIMAL(14,4) NULL,
    volume_especie            VARCHAR(50) NULL,
    volume_numero             VARCHAR(30) NULL,
    volume_marca               VARCHAR(50) NULL,
    volume_peso_liquido        DECIMAL(14,4) NULL,
    volume_peso_bruto          DECIMAL(14,4) NULL,
    id_transportadora          INT NULL,
    chave_nfe                  VARCHAR(50) NULL,
    data_cancelamento_nfe      DATETIME NULL,
    autorizacao_datahora       DATETIME NULL,
    protocolo_nfe               VARCHAR(50) NULL,
    protocolo_nfe_canc          VARCHAR(50) NULL,
    valor_icms                  DECIMAL(14,4) NULL,
    icms_st                     DECIMAL(14,4) NULL,
    valor_ipi                   DECIMAL(14,4) NULL,
    base_icms                   DECIMAL(14,4) NULL,
    base_icms_sub                DECIMAL(14,4) NULL,
    base_ipi                     DECIMAL(14,4) NULL,
    valor_pis                    DECIMAL(14,4) NULL,
    valor_cofins                 DECIMAL(14,4) NULL,
    vr_seguro                    DECIMAL(14,4) NULL,
    vr_gnre                      DECIMAL(14,4) NULL,
    id_finalidade_venda          INT NULL,
    finalidade_venda              VARCHAR(100) NULL,
    id_vendedor                   INT NULL,
    id_vendedor2                  INT NULL,
    canal_venda                    VARCHAR(150) NULL,
    v_fcp_uf_dest                  DECIMAL(14,4) NULL,
    v_icms_uf_dest                  DECIMAL(14,4) NULL,
    v_icms_uf_remet                 DECIMAL(14,4) NULL,
    finalidade_nfe                  VARCHAR(10) NULL,
    observacao_nf                    VARCHAR(500) NULL,
    ref_chave                        VARCHAR(50) NULL,
    ref_numero_docfiscal              VARCHAR(30) NULL,
    ref_serie_docfiscal                VARCHAR(10) NULL,
    deleted     BOOLEAN DEFAULT FALSE,
    synced_at   DATETIME NOT NULL,
    criado_em   DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_nota_emissao (nota_emissao),
    INDEX idx_entrada_saida (entrada_saida),
    INDEX idx_status_nota (status_nota),
    INDEX idx_id_empresa (id_empresa),
    INDEX idx_id_cliente (id_cliente),
    INDEX idx_chave_nfe (chave_nfe),
    INDEX idx_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_nota_fiscal_item (
    id_nota_saida         INT NOT NULL,
    item                  INT NOT NULL,
    id_produto            INT NULL,
    qtde                  DECIMAL(14,4) NULL,
    vr_unitario_bruto     DECIMAL(14,4) NULL,
    vr_total_bruto        DECIMAL(14,4) NULL,
    vr_acrescimo          DECIMAL(14,4) NULL,
    vr_desconto           DECIMAL(14,4) NULL,
    item_cfop             VARCHAR(10) NULL,
    item_cfop_descricao   VARCHAR(255) NULL,
    gera_financeiro       BOOLEAN NULL,
    unidade               VARCHAR(10) NULL,
    id_nota_origem        INT NULL,
    item_origem           INT NULL,
    chave_origem          VARCHAR(50) NULL,
    pedido_venda          VARCHAR(30) NULL,
    ncm                   VARCHAR(20) NULL,
    cst                   VARCHAR(10) NULL,
    base_icms             DECIMAL(14,4) NULL,
    aliquota_icms         DECIMAL(9,4) NULL,
    reducao               DECIMAL(9,4) NULL,
    base_ipi              DECIMAL(14,4) NULL,
    ipi_percentual        DECIMAL(9,4) NULL,
    base_pis              DECIMAL(14,4) NULL,
    aliq_pis              DECIMAL(9,4) NULL,
    base_cofins           DECIMAL(14,4) NULL,
    aliq_cofins           DECIMAL(9,4) NULL,
    difal                 DECIMAL(14,4) NULL,
    fecp                  DECIMAL(14,4) NULL,
    v_icms_uf_dest        DECIMAL(14,4) NULL,
    v_icms_uf_remet       DECIMAL(14,4) NULL,
    v_fcp_uf_dest         DECIMAL(14,4) NULL,
    v_fcp_st              DECIMAL(14,4) NULL,
    vr_frete              DECIMAL(14,4) NULL,
    frete_seller          DECIMAL(14,4) NULL,
    vr_seguro             DECIMAL(14,4) NULL,
    vr_outros             DECIMAL(14,4) NULL,
    valor_ipi              DECIMAL(14,4) NULL,
    valor_icms              DECIMAL(14,4) NULL,
    valor_pis                DECIMAL(14,4) NULL,
    valor_cofins              DECIMAL(14,4) NULL,
    icms_st                    DECIMAL(14,4) NULL,
    valor_comissao_ml           DECIMAL(14,4) NULL,
    vr_item_liquido              DECIMAL(14,4) NULL,
    deleted   BOOLEAN DEFAULT FALSE,
    synced_at DATETIME NOT NULL,
    PRIMARY KEY (id_nota_saida, item),
    INDEX idx_id_produto (id_produto),
    INDEX idx_pedido_venda (pedido_venda),
    INDEX idx_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sysemp_estoque_fisico (
    id_produto                INT NOT NULL,
    id_empresa                INT NOT NULL,
    protocolo_estoque          VARCHAR(30) NULL,
    codigo_produto_pai         INT NULL,
    estoque_minimo             DECIMAL(14,4) NULL,
    estoque_maximo             DECIMAL(14,4) NULL,
    saldo_disponivel           DECIMAL(14,4) NULL,
    estoque_reservado          DECIMAL(14,4) NULL,
    estoque_principal          DECIMAL(14,4) NULL,
    estoque_importacao         DECIMAL(14,4) NULL,
    estoque_avarias            DECIMAL(14,4) NULL,
    estoque_loja               DECIMAL(14,4) NULL,
    estoque_assistencia        DECIMAL(14,4) NULL,
    estoque_armazem_externo    DECIMAL(14,4) NULL,
    custo_formacao             DECIMAL(14,4) NULL,
    custo_medio                DECIMAL(14,4) NULL,
    deleted     BOOLEAN DEFAULT FALSE,
    synced_at   DATETIME NOT NULL,
    criado_em   DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_produto, id_empresa),
    INDEX idx_id_empresa (id_empresa),
    INDEX idx_protocolo_estoque (protocolo_estoque),
    INDEX idx_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- Mercado Livre ----

CREATE TABLE IF NOT EXISTS ml_conta (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    user_id_ml      BIGINT NOT NULL,
    nickname        VARCHAR(100) NOT NULL DEFAULT '',
    access_token    TEXT NOT NULL,
    refresh_token   TEXT NOT NULL,
    expira_em       DATETIME NOT NULL,
    scopes          VARCHAR(255) NOT NULL DEFAULT '',
    criado_em       DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ml_user (user_id_ml)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ml_pedido (
    id_pedido               BIGINT PRIMARY KEY,
    user_id_ml               BIGINT NOT NULL,
    pack_id                  BIGINT NULL,
    status                   VARCHAR(30) NOT NULL,
    status_detalhe           VARCHAR(80) NULL,
    canal                    VARCHAR(30) NOT NULL DEFAULT '',
    data_criacao             DATETIME NOT NULL,
    data_fechamento          DATETIME NULL,
    data_ultima_atualizacao  DATETIME NULL,
    valor_total              DECIMAL(14,2) NOT NULL DEFAULT 0,
    valor_pago               DECIMAL(14,2) NOT NULL DEFAULT 0,
    frete                    DECIMAL(14,2) NOT NULL DEFAULT 0,
    valor_devolvido          DECIMAL(14,2) NOT NULL DEFAULT 0,
    moeda                    CHAR(3) NOT NULL DEFAULT 'BRL',
    comprador_id              BIGINT NULL,
    comprador_nickname        VARCHAR(100) NOT NULL DEFAULT '',
    shipping_id                BIGINT NULL,
    tags                       VARCHAR(500) NOT NULL DEFAULT '',
    atualizado_em              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ml_ped_conta_data (user_id_ml, data_criacao),
    INDEX idx_ml_ped_data (data_criacao),
    INDEX idx_ml_ped_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ml_pedido_item (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    id_pedido       BIGINT NOT NULL,
    item_id         VARCHAR(20) NOT NULL,
    variacao_id     BIGINT NULL,
    titulo          VARCHAR(255) NOT NULL DEFAULT '',
    sku             VARCHAR(100) NOT NULL DEFAULT '',
    categoria       VARCHAR(30) NOT NULL DEFAULT '',
    qtde            INT NOT NULL DEFAULT 0,
    preco_unitario  DECIMAL(14,2) NOT NULL DEFAULT 0,
    preco_cheio     DECIMAL(14,2) NULL,
    taxa_venda      DECIMAL(14,2) NULL,
    moeda           CHAR(3) NOT NULL DEFAULT 'BRL',
    INDEX idx_ml_item_pedido (id_pedido),
    INDEX idx_ml_item_sku (sku),
    INDEX idx_ml_item_item (item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---- ETL (camada de consumo) ----

CREATE TABLE IF NOT EXISTS etl_empresa (
    recno         INT AUTO_INCREMENT PRIMARY KEY,
    origem_dados  VARCHAR(6) NOT NULL,
    grupo         VARCHAR(5) NOT NULL,
    cd_filial     INT NOT NULL,
    dc_filial     VARCHAR(80) NOT NULL,
    dc_fantasia   VARCHAR(25) NOT NULL,
    cnpj          VARCHAR(20) NOT NULL,
    ie            VARCHAR(20) NOT NULL,
    atualizado_em DATETIME NOT NULL,
    UNIQUE KEY uq_grupo_filial (origem_dados, grupo, cd_filial),
    UNIQUE KEY uq_filial (origem_dados, cd_filial)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS etl_produto (
    recno         INT AUTO_INCREMENT PRIMARY KEY,
    origem_dados  VARCHAR(6) NOT NULL,
    cd_produto    VARCHAR(30) NOT NULL,
    dc_produto    VARCHAR(100) NOT NULL,
    um            CHAR(2) NOT NULL,
    ncm           VARCHAR(10) NOT NULL,
    marca         VARCHAR(20) NOT NULL,
    atualizado_em DATETIME NOT NULL,
    UNIQUE KEY uq_produto (origem_dados, cd_produto)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS etl_fatcom (
    recno             INT AUTO_INCREMENT PRIMARY KEY,
    origem_dados       VARCHAR(6) NOT NULL,
    grupo_empresa       VARCHAR(5) NOT NULL,
    cd_filial            INT NOT NULL,
    nf                    VARCHAR(9) NOT NULL,
    serie                 VARCHAR(3) NOT NULL,
    item                  INT NOT NULL,
    cd_produto            VARCHAR(50) NOT NULL,
    dc_filial             VARCHAR(25) NOT NULL,
    periodo               CHAR(6) NOT NULL,
    dt_movto              DATE NOT NULL,
    ent_sai               CHAR(1) NOT NULL,
    status_nf             VARCHAR(50) NOT NULL,
    ctrl_financeiro        CHAR(1) NOT NULL,
    cd_clifor              VARCHAR(20) NOT NULL,
    dc_clifor               VARCHAR(100) NOT NULL,
    uf                       CHAR(2) NOT NULL,
    dc_produto               VARCHAR(100) NOT NULL,
    um                        CHAR(2) NOT NULL,
    ncm                        VARCHAR(15) NOT NULL,
    marca                      VARCHAR(50) NOT NULL,
    canal                       VARCHAR(50) NOT NULL,
    cfop                        VARCHAR(5) NOT NULL,
    cst                          CHAR(3) NOT NULL,
    qtde                          FLOAT NOT NULL,
    vu_merc                       FLOAT NOT NULL,
    vt_merc                       FLOAT NOT NULL,
    vb_icms                       FLOAT NOT NULL,
    aliq_icms                     FLOAT NOT NULL,
    aliq_icms_calc                FLOAT NOT NULL,
    aliq_red_icms                 FLOAT NOT NULL,
    vt_icms                       FLOAT NOT NULL,
    vt_icms_st                    FLOAT NOT NULL,
    vt_icms_st_gnre                FLOAT NOT NULL,
    vt_icms_difal                  FLOAT NOT NULL,
    vt_icms_frete                  FLOAT NOT NULL,
    vb_ipi                          FLOAT NOT NULL,
    aliq_ipi                        FLOAT NOT NULL,
    vt_ipi                          FLOAT NOT NULL,
    vb_pis                          FLOAT NOT NULL,
    aliq_pis                        FLOAT NOT NULL,
    vt_pis                          FLOAT NOT NULL,
    vb_cofins                       FLOAT NOT NULL,
    aliq_cofins                     FLOAT NOT NULL,
    aliq_piscof_calc                 FLOAT NOT NULL,
    vt_cofins                        FLOAT NOT NULL,
    vt_encargos                      FLOAT NOT NULL,
    vt_frete                          FLOAT NOT NULL,
    vt_desconto                       FLOAT NOT NULL,
    vt_nota                           FLOAT NOT NULL,
    vt_liquido                        FLOAT NOT NULL,
    vt_liq_final                      FLOAT NOT NULL,
    vt_custo                           FLOAT NOT NULL,
    vb_tx_fatur                        FLOAT NOT NULL,
    taxa_fatur                         FLOAT NOT NULL,
    vt_tx_fatur                        FLOAT NOT NULL,
    vt_add_frete                       FLOAT NOT NULL,
    vt_rebate                          FLOAT NOT NULL,
    atualizado_em                      DATETIME NOT NULL,
    UNIQUE KEY uq_fatcom (origem_dados, grupo_empresa, cd_filial, nf, serie, item, cd_produto),
    INDEX idx_dt_movto (dt_movto),
    INDEX idx_periodo (periodo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
